### ISSUE TITLE
BUG：添加订阅之后，也查询到了，但是没有后续了

### ISSUE THREAD

**Issue by GodD6366** [pofey/movie-robot-frontend#30]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/17250383/166129394-f727f822-cef9-4c3f-8023-51cef18ad182.png">

应该是下第一个才对，看日志也没发现报错

<img width="766" alt="image" src="https://user-images.githubusercontent.com/17250383/166129514-062ca7c9-9984-489f-8779-202e745faefe.png">

**Comment by pofey** [comment]
第一个中文名前缀太多了，认为不是。种子名的英文名和tmdb英文名也不一样，所以排出不下。
